#!/bin/bash
set -euo pipefail

./mfc.sh run /blue/bala1s/m.vandenboom/1sphere/case.py \
	--name 1sphere \
	--mpi \
	--partition hpg-b200 \
	--nodes 1 \
	--tasks-per-node 3 \
	--email m.vandenboom@ufl.edu \
	--walltime 3:00:00 \
	--account bala1s \
	--engine batch \
	--computer hipergator \
	--no-debug \
	--gpu acc
